### ISSUE TITLE
Continue the developing of the F-Droid version

### ISSUE THREAD

**Issue by AlphaOmega3** [MajeurAndroid/Android-Applications-Info#15]

**Comment by MajeurAndroid** [comment]
I don't understand what you want, you want this app on fdroid ?

**Comment by AlphaOmega3** [comment]
The app is already on F-Droid, but it stops at version 1.5 (2015), while in the Play Store there are the new version. I would like to ask you to also load the new version on F-Droid, please

(Sorry for my bad english, I use Google Translate)

**Comment by krt16s** [comment]
Ref: https://github.com/MajeurAndroid/Android-Applications-Info/issues/11

**Comment by AlphaOmega3** [comment]
The new version is on F-Droid, I thank you for availability!
